# Generated by Django 5.2.10 on 2026-01-11 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_article_donation_newsletter_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('home_eta', 'Home_ETA'), ('home_other', 'Home_Other'), ('curious', 'Curious'), ('analyst', 'Analyst'), ('advocate', 'Advocate'), ('resources', 'Resources')], help_text='Unique identifier for this placement', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of where this placement appears')),
            ],
            options={
                'verbose_name': 'Document Location',
                'verbose_name_plural': 'Document Locations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description shown on frontend'),
        ),
        migrations.AddField(
            model_name='document',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher numbers appear first'),
        ),
        migrations.CreateModel(
            name='DocumentLocationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within this location (lower = appears first)')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_assignments', to='documents.document')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_assignments', to='documents.documentlocation')),
            ],
            options={
                'verbose_name': 'Document Location',
                'verbose_name_plural': 'Document Locations',
                'ordering': ['location', 'order'],
                'unique_together': {('document', 'location')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='locations',
            field=models.ManyToManyField(blank=True, help_text='Select where this document appears', through='documents.DocumentLocationAssignment', to='documents.documentlocation'),
        ),
    ]
